#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_machineoutil:
    path: /machineoutil
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\MachineOutilController::createMachineOutil